version: "3"
services:
  postgres:
    container_name: postgres_gd
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    env_file:
      ./.env

  nginx:
    depends_on:
      - ssr
      - sockets
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"

  ssr:
    build:
      dockerfile: DockerfileSSR
      context: ./app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/gamedev_db
      NODE_ENV: production
    restart: always
    env_file:
      ./.env

  sockets:
    build:
      dockerfile: DockerfileSockets
      context: ./app
    environment:
      NODE_ENV: production
    restart: always
    env_file:
      ./.env

  pgadmin:
    container_name: pgadmin_gd
    image: dpage/pgadmin4:4.18
    restart: always
    env_file:
      ./.env
    environment:
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin-data:

networks:
  default:
    driver: bridge
