version: '3'

services: 
    bomb-app:
        build:
            context: .
        depends_on:
            - postgres
        ports: 
            - "5000:5000"
        restart: always
        environment:
            env_file:
                ./dev.env
        networks: 
            - app-network

    postgres: 
        image: postgres:12
        ports: 
            - "5432:5432"
        volumes: 
            - ./postgres/data:/var/lib/postgresql/data
        restart: always
        environment:
            env_file:
                ./dev.env
        networks: 
            - app-network

                  
networks:
    app-network:
        driver: bridge